services:
  web:
    build: .
    environment:
      - NODE_ENV=production
      - MONGODB_URI=mongodb+srv://hackfleet:gz1EWM0mYnLzOBlg@atlascluster.0d2q4pl.mongodb.net/
      - PORT=4000
    ports:
      - "4000:4000"
